### ISSUE TITLE
Missing implementation

### ISSUE THREAD

**Issue by kbakdev** [Romain-P/Wotlk-Scripts#1]
Hey, could you explain more about how your scripts work and how to implement them? I'm really curious and I'm not quite able to understand how it works.

**Comment by Romain-P** [comment]
You basically have to
1) Find an unlocker in order to unlock lua protected api
2) Load the scripts somehow

Since the scripts are too big to be inside a macro, you might want to use something like `SuperDuperMacro` or similar
Since most of tlk are protected against gagarin/pqr I'd recommand to use an undetected but paid one e.g `ewtwow.com`

**Comment by kbakdev** [comment]
Okay, I found lua unlocker, I uploaded the whole script as a macro, but do I need to change anything? Should I just paste the script as a macro?

I just tried to paste it, but the script does not load and sends messages in the chat.

**Comment by kbakdev** [comment]
Ah... Nevermind. You have to enter the SuperDuperMacro options and create a "script".
Thank you for your reply and I hope that my issue helped others implement this script and learn something new.
